# Generated by Django 4.1 on 2023-12-11 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistset',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='curriculum',
            old_name='title',
            new_name='name',
        ),
    ]
