# Generated by Django 4.1 on 2024-02-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='order',
            field=models.IntegerField(),
        ),
    ]
