# Generated by Django 4.1 on 2023-12-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_rename_title_checklistset_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='name',
            new_name='title',
        ),
    ]
