# Generated by Django 4.1 on 2024-02-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_postperiod_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postperiod',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.post'),
        ),
        migrations.CreateModel(
            name='PostEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.post')),
            ],
        ),
    ]
