# Generated by Django 4.1 on 2024-02-01 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_checklist_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='order',
            new_name='sequence',
        ),
    ]
