# Generated by Django 4.2.9 on 2024-01-09 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0003_remove_evaluationitem_curriculum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluationitem",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.subject"
            ),
        ),
    ]
