# Generated by Django 4.1 on 2024-02-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_rename_order_checklist_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='confirmed_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
