# Generated by Django 4.1 on 2024-02-05 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_postevaluationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='type',
            field=models.CharField(default='hand', max_length=100),
        ),
        migrations.AlterField(
            model_name='checklistrecord',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.post'),
        ),
    ]
