# Generated by Django 4.2.9 on 2024-01-09 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0004_alter_evaluationitem_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evaluationitem",
            name="subject",
        ),
        migrations.AddField(
            model_name="evaluationitem",
            name="curriculum",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.curriculum",
            ),
        ),
    ]
