# Generated by Django 4.1 on 2024-02-01 03:51

from django.db import migrations, models
import django.db.models.deletion
import models.models as modelsmodels


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_enrollment_confirmed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=modelsmodels.dynamic_upload_to)),
                ('filename', models.CharField(max_length=100)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.assignment')),
            ],
        ),
    ]
