# Generated by Django 4.1 on 2024-02-05 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0005_checklist_type_alter_checklistrecord_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postevaluation',
            name='post',
        ),
        migrations.AddField(
            model_name='postevaluation',
            name='child_post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eval_child_post', to='models.post'),
        ),
        migrations.AddField(
            model_name='postevaluation',
            name='parent_post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eval_parent_post', to='models.post'),
        ),
        migrations.AddField(
            model_name='postevaluation',
            name='target',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
