# Generated by Django 4.1 on 2024-02-01 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0006_remove_checklistrecord_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistrecord',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.curriculum'),
        ),
        migrations.AlterField(
            model_name='checklistrecord',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_target', to=settings.AUTH_USER_MODEL),
        ),
    ]
