# Generated by Django 4.1 on 2024-02-05 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_remove_postevaluation_post_postevaluation_child_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postevaluation',
            name='child_post',
        ),
        migrations.RemoveField(
            model_name='postevaluation',
            name='parent_post',
        ),
        migrations.AddField(
            model_name='postevaluation',
            name='post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.post'),
        ),
    ]
