# Generated by Django 5.0.1 on 2024-02-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0007_remove_postevaluation_child_post_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postperiod",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
    ]
