# Generated by Django 4.2.9 on 2024-01-16 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0008_subjectevaluationitems"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubjectEvaluationItems",
            new_name="SubjectEvaluationItem",
        ),
    ]
