# Generated by Django 4.1 on 2024-02-01 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_alter_journal_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.subject'),
        ),
    ]
