# Generated by Django 4.2.9 on 2024-01-16 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0010_subjectevaluationitem_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectevaluationitem",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.subject"
            ),
        ),
    ]
