# Generated by Django 4.2.9 on 2024-01-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0011_alter_subjectevaluationitem_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectevaluationitem",
            name="percentage",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
