# Generated by Django 4.1 on 2024-02-04 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_journal_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='location',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.subject'),
        ),
    ]
