# Generated by Django 4.2.9 on 2024-01-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0012_alter_subjectevaluationitem_percentage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subjectevaluationitem",
            old_name="curriculum",
            new_name="curriculum_type",
        ),
        migrations.AlterField(
            model_name="subjectevaluationitem",
            name="percentage",
            field=models.IntegerField(default=0),
        ),
    ]
