# Generated by Django 4.2.9 on 2024-01-17 11:14

from django.db import migrations, models
import models.models as models_models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0014_assignment_eval_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentfile",
            name="file",
            field=models.FileField(upload_to=models_models.dynamic_upload_to),
        ),
        migrations.AlterField(
            model_name="curriculumfile",
            name="file",
            field=models.FileField(upload_to=models_models.dynamic_upload_to),
        ),
    ]
