# Generated by Django 4.2.9 on 2024-01-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0015_alter_assignmentfile_file_alter_curriculumfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentfile",
            name="filename",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="curriculumfile",
            name="filename",
            field=models.CharField(default="", max_length=100),
        ),
    ]
